version: "3"

services:
  # Serviço que irá rodar o node
  node:
    # Faz o build do Dockerfile da pasta atual e utiliza o resultado desse build
    # como a imagem do container
    build: .
    # Define um user específico, diferente de root para a execução dos comandos
    # user: eval
    # Nome do container para facilitar execução
    container_name: fakeDataApi
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    command: bash
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./:/app
    # Lista de serviços do qual este serviço depende
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3000:3000
    # Configura as variáveis de ambiente dentro do container
    environment:
      API_HOST: 'node'
      API_PORT: 3003
      NODE_ENV: 'development'
      JWT_SECRET: secretJWT
    networks:
      - fakeDataApi


